name: Check Code Formatting
on:
  workflow_call:
jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clang-format check
        id: clang-format
        uses: ./.forgejo/actions/run-clang-format
        with:
          failCondition: error

  gersemi:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
      - name: gersemi Check
        id: gersemi
        uses: ./.forgejo/actions/run-gersemi
        with:
          failCondition: error