name: Push
run-name: ${{ github.ref_name }} push run
on:
  push:
    branches:
      - master
      - main
      - 'release/**'
    paths:
      - build-aux/**
      - cmake/**
      - data/**
      - src/**
      - .github/workflows/push.yaml
    tags:
      - '*'
permissions:
  contents: write
jobs:
  check-format:
    name: Formatting Check
    if: github.ref_name == 'master' || github.ref_name == 'main'
    uses: ./.github/workflows/check-format.yaml
    permissions:
      contents: read

  build-project:
    name: Build
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
    permissions:
      contents: read